### ISSUE TITLE
Outdated Taiko

### ISSUE THREAD

**Issue by waterweasel4** [softrams/gauge-taiko-steps#19]
We have an issue within CMSART that uses this repo that is showing taiko is pinned to version 1.0.25 but there are vulnerabilities in it that are fixed in version 1.3.2.  Can we get this updated please?

ansi-html Regular Expression Denial of Service (ReDoS)
axe-core 
unset-value Prototype Pollution
glob-parent Regular Expression Denial of Service (ReDoS)

**Comment by mkmurali** [comment]
Fixed with PR #20.
